sudo: required
services:
- docker
matrix:
  include:
  - language: node_js
    node_js:
    - 12
    before_install:
    - docker version
    - docker info
    install:
    - npm install
    before_script:
    - node --version
    - npm --version
    script:
    - npm test
    after_success:
    - docker build -t filippandza/medical-images-client:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push filippandza/medical-images-client:latest
  - language: python
    python:
    - 3.6
    before_install:
    - openssl aes-256-cbc -K $encrypted_4518de6137f4_key -iv $encrypted_4518de6137f4_iv -in devopslab.pem.enc -out devopslab.pem -d
    install:
    - pip install ansible
    script:
    - chmod 600 devopslab.pem
    - ansible-playbook -i ansible/aws_hosts ansible/playbook_cicd.yml
env:
  global:
  - secure: x2uy+2n9twUSzTvYmewDiKtjYQhxCeyTYNsB1aXpDcpK5Ev/6PX9lUDO2soqTXRR5MtD9QvCFiruvjNHGZs/XOZDAGKVzsZj4wfasoJSVBYol0rAcYY6CMjJkU1wWfTSGmhXVBPE/GPT0BxYQwY6LyHRmCyaqk7so+M9D1vPaRo5h3nqfwKCWk5GtXkq555CKC1HG2RxgAvdcIKcxx3M1l4huuFDqeYnZ9UzaHKmN7jIV9z/2SqS0TDKz65NxwoAuzkNk0kNNZLTURIF0EA3gEh0sFj1vlVwCnwkeOBOFR9ZGMKbkXp84U4KWveyqjZ19+CLWlGgTAUbJI+9m8jXXCeMr3iAh9WmhwuUibSRbRVVxQq7NB/Snc4dsaVJHWqPDVbErZOlMzgJ+afWpZFmcSYBGHgw1nvOSirrkGRItWNsZuzBlApNAyCAIq+a8Iul4W84Qgc/oHQ73ZcD0fm9kp27FTFCy5DF4yFH5klebiZKVJUfU7QjyF/pI/pLuZUiTWZytOrrf1u6C+tIoYyPTmPbtgHRW6pxx6H/gab42MtjcyY5XPokM8J7KMm+UZ6/IaGnyKzxKyYlS4owB73xau6bJ3khQrR5vemb55sJjCDFMW0wgKhJmOvLNPFcE2uhbDvl4v5lf/XpU3iw8fFzRmrWaZiRH1z5ipbtcczwBW4=
  - secure: 1E/QTjaFI01Dins0IC6vA+lsxUogTond86JDygUeF+uBTMwOjLOboXxMrSoEFpgK+jfW1lBY+K5R+w5z3fbXoXiGDdudbwBLfNSW6NVgs8Rj5xvbbua16CGxYYh3GIlU+cNQUkeKts8D/zE7culANKN/oM71Do+m8ngVgO0KtLODZDUjmj9H5RC20sf2XHu+UcvEe9Y01hRJD8qH1L9D1BIzci3Fh2pXNNmY0pL/fistiObN+wwoG0FcytGaew7yVXIWnmcFLF8LYAJDVx1hOulClsT5D+Ep3oHo0xplvs1RZLNTggLskosIxXlRNECEl/6ZdkamR/6Plpg2wmrBLI3i/e4WjqDW7sVi5JSagofBxsYL5kZX8otVsZt+r3ROm46TlWrFtsgMFUYKV/m9wgpEw+yV6KDljeC4TSg86QhmILyCX47Q/fp9qVCsCsZ9ynnxN86gL6hPq82ilbJpxRXwu4xqMzV0dQkX110nF5RHkVHhX7IlxP1eXhNMDhG0r1jdvK3oStHkEjL4VvUGgR40VxudNZpFIrwH4Y9QCxaridxkOLIW0qz5baOOyR1CwOdqrQz3ufH77M1mEcCPXnwKwrS99GKjmPhjFqGjNESt1aL8pGXf1lAYvwJIIdddfTruAm/+nswCCrXh3GO8Zlv4MDtaHGSxuYvKM/+FhnE=
