sudo: required
services:
- docker
matrix:
  include:
  - language: node_js
    node_js:
    - 12
    before_install:
    - docker version
    - docker info
    install:
    - npm install
    before_script:
    - node --version
    - npm --version
    script:
    - npm test
    after_success:
    - docker build -t filippandza/medical-images-client:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push filippandza/medical-images-client:latest
  - language: python
    python:
    - 3.6
    before_install:
    - openssl aes-256-cbc -K $encrypted_4518de6137f4_key -iv $encrypted_4518de6137f4_iv -in devopslab.pem.enc -out devopslab.pem -d
    install:
    - pip install ansible
    script:
    - chmod 600 devopslab.pem
    - ansible-playbook -i ansible/aws_hosts ansible/playbook_cicd.yml
env:
  global:
  - secure: FYQp3TbIJF/HEbhc6bfgj9rCB3y83E/oYdlNTEyDgk/CZofQUx1WWaK0yqO/wKU43C7iDma7MyTTmI2/OzbXj4kgL6iXVedwER4LBP5V+E64gAK9m5cvDIyC1jtJH6cpIhuFeww1XhHadNl+eZTgk0N+PjRhRcR4A1UXWdWZMkZoXuft/hngr7gvmEp/p2nQPShsbzzKq0i86NbOzd/yrlsiLuB97xV+E0xTPYLY/dK8mX9TT1BvF6VIQNhQffPBGAsgKhP16EQKXT5FMLfXH7lkwnAe3tkAySSNFvXgYivljv5mfPdYjF6kqcqR2YJGYCW6p96F1+HTVvGCxOAEx49hwDiFIRTW8XzAR+SOD/xhH8zRsldlENBmfCRLXLIQGZ2pOxStxzq7tr2p8kOei9v2COyI1d1RW47YXyVQJ0JRkSFUmY0He+VC3zhtlyzHyQr0XDcsX2Rkks0HV/EIRTWBDlMRHi0sgxKBksB8gHluriCKll8IDudHOkY3sF9HC8S0+o12kzOQ6aC/WvtTgt7wVTl8bci7dPlGZfh9bftRs8+bdQ6silbbYv4hlVImXxilH5NpBXhfnESbO3YFsZTn24XxTseSiKxORTXTIEMv9AY0YvxRFy6451V7n8DfWcr5V6AY3SRG+RlEHKx1YnwTI7WKE+vYt7OqpdjrVlQ=
  - secure: fUc8Brx+zGxebpDLqyUI8J3rH5zkK4+2ywJscB6Yy9ZuaqT3AGgydB+j6MJugPdXtUJSC2vvpcMRCqRsi8dhfXQv3aQ8gi3CfDZcuPUjeWvdYImBmdxtRdmMDkP6rrXNVMlDpT+IWnZFt594gfEhSdvcSPihEkHGYu5DA00DAH4Oot5jQ6qLCHVQz5Lbpfp3JEvI/YF2Mm0poFhf24HG/FSpUZipv8CtfTgZtqHRP4FZm7NB799z5dsJ3CrSLJ/0JLvUBU0bj3sQLkoE2Nj5+373B8wG2dGvFThw1FADDd+CYn9j0Mzs+bsNJ+Qs2hN5PifIS/9RQwUxIINzmeK3kuapBbxKGhFbVTM72RHGf3f3jj4UaQYj7emDolHkr7Kqgg0EWyeEl1Hsv7+9iZFi3VdAaAXsvc3jxordVIZ14rn8f4HepGmdPI3kdjhkDzxtCkyek/SK9S6JazOGA/wXdx0W0z8NXaTILrNe5i9kZMtcnzjXFCTlvOm03ucdx3fOO6jZJxtv/Cxyn1Vy5HRP7osBSf6Edf5LD2UxBsTKvZNEszzt2G0qvAP5KF+yJZkOtoBSo4HiDO4mTEhstVaA+9pWYyImPWzD5IoOcMsOCbM1EjRtP+IM4wfKDFe4H7IyBzRxvNlmZ+RmLs7AiGlFMqA3U25A3YVm0l8Tf1cJsnk=

