
#Children names:
#aws-ubuntu-test
#aws-ubuntu-prod

- hosts : aws-ubuntu-test
  become : yes
  gather_facts : False
  tasks :
    #true flag so it doesn't return error if they don't exist
    - name: Stop container process, delete container, and delete image
      shell: docker stop osg-client || true && docker rm osg-client || true && docker rmi filippandza/medical-images-client || true

    - name: Pull docker image
      shell: docker pull filippandza/medical-images-client

    - name: Create client directory if it does not exist
      become: no
      file:
        path: ~/client
        state: directory
        mode: '0755'
        owner: "ubuntu"
        group: "ubuntu"

    - name: Copy Docker-Compose file
      become: no
      copy:
        src: ./test/docker-compose.yml
        dest: ~/client/docker-compose.yml
        mode: '0644'

    - name: Start services with docker-compose
      shell: cd /home/ubuntu/client && docker-compose up -d
